name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t my-nginx-site-test .

    - name: Run container
      run: docker run -d -p 8080:80 --name test-container my-nginx-site-test

    - name: Wait for Nginx to start
      run: sleep 3

    - name: Test Nginx
      run: curl -I http://localhost:8080

    - name: Stop container
      run: docker stop test-container